services:
  postgres:
    image: postgres:18-alpine
    container_name: school_inventory_postgres
    restart: always
    environment:
      POSTGRES_DB: school_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    image: node:22-alpine
    container_name: school_inventory_auth_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:auth"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      AUTH_SERVICE_PORT: 5001
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5001:5001"

  user-service:
    image: node:22-alpine
    container_name: school_inventory_user_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:user"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      USER_SERVICE_PORT: 5002
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5002:5002"

  admin-service:
    image: node:22-alpine
    container_name: school_inventory_admin_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:admin"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      ADMIN_SERVICE_PORT: 5003
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5003:5003"

  equipment-service:
    image: node:22-alpine
    container_name: school_inventory_equipment_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:equipment"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      EQUIPMENT_SERVICE_PORT: 5004
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5004:5004"

  request-service:
    image: node:22-alpine
    container_name: school_inventory_request_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:request"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      REQUEST_SERVICE_PORT: 5005
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5005:5005"

  report-service:
    image: node:22-alpine
    container_name: school_inventory_report_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:report"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      REPORT_SERVICE_PORT: 5006
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5006:5006"

  spatial-service:
    image: node:22-alpine
    container_name: school_inventory_spatial_service
    working_dir: /app/backend
    command: sh -c "npm install && npm run svc:spatial"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: school_inventory
      DB_HOST: postgres
      DB_PORT: 5432
      SPATIAL_SERVICE_PORT: 5007
      JWT_SECRET: super_secret_key_change_this
    volumes:
      - ..:/app
    depends_on:
      - postgres
    ports:
      - "5007:5007"

  api-gateway:
    image: node:22-alpine
    container_name: school_inventory_api_gateway
    working_dir: /app/backend
    command: sh -c "npm install && npm run gateway:start"
    environment:
      NODE_ENV: development
      API_GATEWAY_PORT: 5000
      AUTH_SERVICE_URL: http://auth-service:5001
      USER_SERVICE_URL: http://user-service:5002
      ADMIN_SERVICE_URL: http://admin-service:5003
      EQUIPMENT_SERVICE_URL: http://equipment-service:5004
      REQUEST_SERVICE_URL: http://request-service:5005
      REPORT_SERVICE_URL: http://report-service:5006
      SPATIAL_SERVICE_URL: http://spatial-service:5007
    volumes:
      - ..:/app
    depends_on:
      - auth-service
      - user-service
      - admin-service
      - equipment-service
      - request-service
      - report-service
      - spatial-service
    ports:
      - "5000:5000"

volumes:
  postgres_data:

