import React, { useRef } from 'react';
import Barcode from 'react-barcode';
import { X, Download, LayoutPanelLeft } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  equipmentName: string;
  serialNumber: string;
}

export const BarcodeModal: React.FC<Props> = ({ isOpen, onClose, equipmentName, serialNumber }) => {
  const barcodeRef = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    if (!barcodeRef.current) return;
    
    // Find the SVG element generated by react-barcode
    const svg = barcodeRef.current.querySelector('svg');
    if (!svg) return;

    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    img.onload = () => {
      // Barcode is usually wider than tall
      canvas.width = 600;
      canvas.height = 300;
      if (!ctx) return;
      
      // Background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, 600, 300);
      
      // Draw centered
      ctx.drawImage(img, 50, 50, 500, 150);
      
      // Label
      ctx.fillStyle = '#1d1d1f';
      ctx.font = 'bold 20px system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(equipmentName, 300, 230);
      
      ctx.fillStyle = '#86868b';
      ctx.font = '14px system-ui, sans-serif';
      ctx.fillText(`SN: ${serialNumber} | SIMS Inventory`, 300, 260);
      
      URL.revokeObjectURL(url);
      const link = document.createElement('a');
      link.download = `barcode-${serialNumber}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    };
    img.src = url;
  };

  if (!serialNumber) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[200] flex items-end sm:items-center justify-center p-0 sm:p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/70 backdrop-blur-xl"
          />
          <motion.div
            initial={{ y: '100%', opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: '100%', opacity: 0 }}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
            className="relative w-full max-w-xl bg-white dark:bg-[#1d1d1f] sm:rounded-[32px] rounded-t-[32px] shadow-2xl border border-[#d2d2d7] dark:border-[#303030] overflow-hidden p-8 flex flex-col items-center gap-6"
          >
            <button
              onClick={onClose}
              className="absolute top-5 right-5 p-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            >
              <X size={20} className="text-[#86868b]" />
            </button>

            <div className="flex flex-col items-center gap-2">
              <div className="w-10 h-10 rounded-2xl bg-indigo-500/10 flex items-center justify-center">
                <LayoutPanelLeft size={20} className="text-indigo-600 dark:text-indigo-400" />
              </div>
              <h3 className="font-black text-lg uppercase tracking-wider text-[#1d1d1f] dark:text-white text-center">
                {equipmentName}
              </h3>
              <p className="text-[10px] font-bold text-[#86868b] uppercase tracking-widest">
                Inventory Barcode (Code128)
              </p>
            </div>

            <div ref={barcodeRef} className="p-8 bg-white rounded-3xl shadow-lg border border-[#f5f5f7] flex items-center justify-center w-full overflow-hidden">
              <Barcode 
                value={serialNumber} 
                width={2}
                height={100}
                format="CODE128"
                displayValue={true}
                fontSize={14}
                background="#ffffff"
                lineColor="#1d1d1f"
                margin={0}
              />
            </div>

            <div className="w-full space-y-3">
              <button
                onClick={handleDownload}
                className="w-full flex items-center justify-center gap-2 py-4 bg-[#1d1d1f] dark:bg-[#f5f5f7] text-white dark:text-[#1d1d1f] rounded-2xl font-black text-[10px] uppercase tracking-widest hover:opacity-90 active:scale-95 transition-all shadow-xl shadow-black/10 dark:shadow-white/5"
              >
                <Download size={14} />
                Download PNG Label
              </button>
              <p className="text-center text-[9px] text-[#86868b] font-medium max-w-[80%] mx-auto">
                Print this label and attach it to the equipment. Use the "Scan Barcode" tool in the dashboard to identify this item.
              </p>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
